services:
  - type: web
    name: spring-boot-app
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATA_MONGODB_URI
        sync: false
