services:
  - type: web
    name: spring-boot-app
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATA_MONGODB_URI
        value: mongodb+srv://Maroun2410:MarounMelhem.2410@cluster0.egwuuje.mongodb.net/finalprojectdb?retryWrites=true&w=majority